name: 每日自动

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0点（北京时间 8点）
  workflow_dispatch:     # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 开启写权限
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 解决权限冲突

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install requests demjson3

      - name: 运行解密脚本
        run: python decrypt.py

      - name: 提交并推送
        uses: EndBug/add-and-commit@v9
        with:
          message: "✅ 自动更新解密后的影视仓配置"
          committer_name: GitHub Actions
          committer_email: actions@github.com
          default_author: github_actions
